feat: (web) ⚡️ add Feed
PintaApis/developars-club pull request #20
Opened 2022-10-06 23:43 UTC by vmga43

:warning: Por favor, antes de crear este Pull Request, asegurate de haber creado un issue en el repositorio.

La discusión sobre la aceptación de este pull request se realizarań por esa vía.

Cualquier Pull Request creada sin un issue de referencia será rechazada automáticamente.

:clipboard: Esta es la lista de cosas que debe cumplir tu Pull Request antes de ser enviada:

- [ ] He leido el [contributing.md](../CONTRIBUTING.md)
- [ ] He leido el [Código de conducta](../CODE_OF_CONDUCT.md)
- [ ] Seguir la guía de estilos del proyecto
- [ ] Los commits de esta Pull Request (PR) van [enlazados con los issues](https://help.github.com/articles/closing-issues-using-keywords/)
- ...

:dart: **[Cerrar issues](https://help.github.com/articles/closing-issues-using-keywords/)**

:pray: Por favor incluye `closes #XXXX` en el comentario de esta Pull Request para auto-cerrar los issues relacionados, si es posible.

**:clap: ¡Gracias por participar en el proyecto!**

2022-10-13 18:01 UTC, carlosazaustre requested changes
Gracias @manologarciadev por el aporte!
Te he dejado unos comentarios para terminar de pulir la PR :)

2022-10-13 18:01 UTC, carlosazaustre commented on packages/ui/index.tsx
> +import Feed from './components/Feed'
Checkar esto cuando lo exportes de manera nombrada.

2022-10-14 03:46 UTC, manologarciadev commented
@carlosazaustre Ya quedaron actuilizados en base a recomendaciones, Saludos!

2022-10-28 07:52 UTC, carlosazaustre approved these changes
✅ Genial!
Perdona la tardanza en hacer el merge.

2022-10-28 07:52 UTC, merged